target-version = "py311"
line-length = 100
src = ["backend"]

[lint]
select = ["E", "F", "I", "UP", "B"]

[lint.isort]
known-first-party = ["backend"]

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]

[lint.per-file-ignores]
"backend/alembic/*" = ["E", "F", "I", "UP"]
