"""create event_log table

Revision ID: 1b5f55a2de5c
Revises: 
Create Date: 2026-06-10 23:13:08.635812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5f55a2de5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_mission_id'), 'event_log', ['mission_id'], unique=False)
    op.create_index(op.f('ix_event_log_severity'), 'event_log', ['severity'], unique=False)
    op.create_index(op.f('ix_event_log_timestamp'), 'event_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_log_timestamp'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_severity'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_mission_id'), table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###
